[package]
name = "royalroad-dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
bpaf = { version = "0.9.9", features = ["derive"] }
ego-tree = "0.6.2"
leaky-bucket = "1.0.1"
regex = "1.10.3"
reqwest = "0.11.24"
scraper = { version = "0.18.1", features = ["deterministic"] }
thiserror = "1.0.57"
tokio = { version = "1.35.1", features = ["macros", "fs"] }
url = "2.5.0"
